### ISSUE TITLE
package ‘ArrayBin’ is not available

### ISSUE THREAD

**Issue by alexthiery** [juliendelile/Antler#2]
Hey Julien, just wanted to let you know that Antler is failing to install as the ArrayBin package seems to have been removed from CRAN.

Can be easily solved by running this first - but thought I would let you know
```
devtools::install_version('ArrayBin', version = '0.2')
```

**Comment by juliendelile** [comment]
Thanks Alex for the feedback, I have edited the installation guidelines accordingly.

**Comment by kuchuan1019** [comment]
Hi Julien, I have tried to follow the guideline to install ArrayBin package but it is still failed. I am using R 4.1.3 and BiocManager 3.14. Could you please let me know how I can install it so to have the Antler install? Thanks.
